baseurl = "https://carrow.me.uk/"
title = "C M W"

[module]
[[module.imports]]
path = "github.com/luizdepra/hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-light"

[params]
info = [
    "",
    "[Projects](/projects/) for the academic work I have undertaken.",
    "",
    "[About](/about/) for my CV.",
    "",
    "[Posts](/posts/) for essays and half-baked ideas.",
]

author = "Carrow Morris-Wiltshire"
description = "Carrow's personal website"
keywords = "blog,developer,personal"
avatarurl = "images/profile.jpeg"
#gravatar = "john.doe@example.com"

faviconSVG = "/img/favicon.svg"
favicon_32 = "/img/favicon-32x32.png"
favicon_16 = "/img/favicon-16x16.png"

since = 2019

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

# customCSS = ["css/custom.css"]
# customSCSS = ["scss/custom.scss"]
# customJS = ["js/custom.js"]

[params.googleTagManager]
id = "G-KG2Z01B12C"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/carrowmw/"
[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/carrow-morris-wiltshire-0492b6188/"

# Menu links
[[menu.main]]
name = "About"
weight = 1
url = "about/"
[[menu.main]]
name = "Projects"
weight = 2
url = "projects/"
[[menu.main]]
[[menu.main]]
name = "Publications"
weight = 4
url = "publications/"
[[menu.main]]
name = "Ongoing"
weight = 5
url = "https://carrowmw.github.io/latex-documents/"
[[menu.main]]
name = "Posts"
weight = 6
url = "posts/"
