languageCode: en-gb
# baseURL: "http://localhost:1313/" # For local testing
# or
baseURL: "https://carrowmw.github.io/carrow.me.uk/" # For GitHub Pages

title: CMW
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45 # implement!

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Carrow Morris-Wiltshire
  # This is shown when website is posted in Discord and other socials
  description: "PhD Student at Geospatial Systems Centre for Doctoral Training, Newcastle University"
  keywords: [Carrow Morris-Wiltshire, Post, Portfolio, Data Science, Geospatial, CDT, Statistics]
  author: Carrow WB Morris-Wiltshire
  # author: ["Me", "You"] # multiple authors
  # Image displayed when posting site link on socials
  # For example, if you post the link to the site in Discord, this image will be displayed
  images: ["images/icon.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false

  # See markup.tableOfContents for configuration
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false

  # See https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#comments
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  # New, from PaperModX
  TocSide: left
  # Enable KaTeX on every page globally. See post post about setting up site
  math: true
  # Without this, archive doesn't show all pages
  # See https://github.com/adityatelange/hugo-PaperMod/issues/912
  # And https://github.com/adityatelange/hugo-PaperMod/commit/fc87fc3a29e8e515dff866159601a734e3ad4a2f
  # Note from https://github.com/adityatelange/hugo-PaperMod/issues/702 that post must have date to be archived
  ShowAllPagesInArchive: true

  # Necessary for post nav links to show up on /posts and /projects
  # https://github.com/adityatelange/hugo-PaperMod/issues/940
  mainSections:
    - about
    - projects
    - posts
    - other

  assets:
    # Disables highlight.js, using Hugo Chroma instead
    # https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
    # Note: Do not enable this. May not work correctly due to some code theme changes made in or around
    # https://github.com/jesse-wei/jessewei.dev-PaperMod/commit/bcadfdde8e12a2a9f9ed853f9939695797b31739
    disableHLJS: true
    # disableFingerprinting: true
    # https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#adding-custom-favicons
    # static/ {favicon.ico, favicon-16x16.png, favicon-32x32.png, apple-touch-icon.png, safari-pinned-tab.svg} automatically detected

  label:
    text: ""
    icon: "images/icon.png"
    iconHeight: 22

  # profile-mode
  profileMode:
    enabled: true
    title: Carrow Morris-Wiltshire
    subtitle: >
      For the academic work I have undertaken as part of my postgraduate journey visit [Projects](/projects/).

      To view my CV - in case you are interested in paying me large sums of money - go to [About](/about/).

      For half-mad ramblings about whatever crosses my mind, see [Posts](/posts/).

    imageUrl: images/picture_bow.png  # Add the relative path to your image in the static folder
    imageWidth: 200  # Set the width of the image as you desire
    imageHeight: 200  # Set the height of the image as you desire
    imageTitle: ""  # Optional: add a title to the image

    buttons:
        - name: Projects
          url: /projects/
        - name: Posts
          url: /posts/


  # home-info mode
  homeInfoParams:
    Title: "\U0001F44B"
    Content: |
      Carrow welcomes you to peruse his pretentionous and self-congratulatory personal website.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/CARROWMW"
    - name: linkedin
      url: "https://www.linkedin.com/in/carrow-morris-wiltshire-0492b6188/"
    - name: github
      url: "https://github.com/carrowmw"
    - name: email
      url: "mailto:carrow.m.w@gmail.com"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
#    URL: "https://github.com/chanin-www/content"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

    # Source: https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#search-page
outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 2
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 3
    - identifier: search
      name: Search
      url: /search/
      weight: 4

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true

# Source: https://gohugo.io/getting-started/configuration-markup/#highlight
# Parameter meanings: https://gohugo.io/functions/highlight/
markup:
  tableOfContents:
    # Without this, Hugo ToC doesn't show h4 and higher
    # https://github.com/alex-shpak/hugo-book/issues/52
    endLevel: 6

  highlight:
      anchorLineNos: false
      codeFences: true
      guessSyntax: true
      hl_Lines: ""
      hl_inline: false
      lineAnchors: ""
      lineNoStart: 1
      # highlight.js also doesn't use line numbers by default.
      # The rationale is that doing so improves readability
      # (https://highlightjs.readthedocs.io/en/latest/line-numbers.html).
      # Therefore, I disable it by default.
      # Note: It's possible to enable it on a specific code block by specifying
      # ``` {lineNos=true}
      # ```
      lineNos: false
      lineNumbersInTable: true
      # false means use external CSS file
      noClasses: false
      noHl: false
      # style: monokai
      tabWidth: 4

