baseurl = "http://www.example.com"
title = "Home"
theme = ["custom-coder-mods", "hugo-coder"]
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
info = [
    "",
    "[Projects](/projects/) for the academic work I have undertaken.",
    "",
    "[About](/about/) if you are interested in paying me large sums of money and need my CV.",
    "",
    "[Posts](/posts/) for half-mad ramblings about anything that crosses my mind.",

    "Carrow",
]

author = "Carrow Morris-Wiltshire"
description = "Carrow's personal website"
keywords = "blog,developer,personal"
avatarurl = "images/picture_bow.png"
#gravatar = "john.doe@example.com"

faviconSVG = "/img/favicon.svg"
favicon_32 = "/img/favicon-32x32.png"
favicon_16 = "/img/favicon-16x16.png"

since = 2019

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

# customCSS = ["css/custom.css"]
# customSCSS = ["scss/custom.scss"]
# customJS = ["js/custom.js"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/carrowmw/"
[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/carrow-morris-wiltshire-0492b6188/"
[[params.social]]
name = "Twitter"
icon = "fa-brands fa-twitter fa-2x"
weight = 3
url = "https://twitter.com/carrowmw/"

# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url = "posts/"
[[menu.main]]
name = "About"
weight = 2
url = "about/"
[[menu.main]]
name = "Projects"
weight = 3
url = "projects/"
